---
relcanonical: "https://yrh.dev"
baseurl: ""
relativeURLs: true
languageCode: "en-us"
title: "Yann Hodique"
footnotereturnlinkcontents: "â†©"
permalinks:
  post: /:year/:month/:title/
  code: /:contentbasename/
Social:
  twitter: yann_hodique
  facebook: yann.hodique
  keybase: sigma
params:
  AuthorName: "Yann Hodique"
  AuthorEmail: "yann.hodique@gmail.com"
  Company: "Google"
  GitHubUser: "sigma"
  LinkedInUser: "hodique"
  StackExchangeId: "392509"
  disqusShortname: "yannhodiqueinfo"
  ResumePdf: "https://sigma.keybase.pub/cv.pdf"
pygmentsCodeFences: true
pygmentsCodeFencesGuessSyntax: true
pygmentsUseClasses: true
...
